### ISSUE TITLE
How to refer to server url for resources data urls ?

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#153]
Right now we store an `serverUrl` config variable in our server to fill the url of resources data such as images or csv. This creates problems on production.

Solution 1 : update prod config by using `serverUrl`

Solution 2 : provide partial url and let the client rebuild correct urls with its config (eg : `/static/:id/:id.jpg` --> `myserverurl.com/static/:id/:id.jpg`)

**Comment by robindemourat** [comment]
Choice arising from discussion :

* remove from server config the `serverUrl` key
* add `/static/` server endpoint separate from api (so that it can be handled by nginx in production mode)
* upstream to the display of images and tables, reconstruct the correct url dynamically
* in `quinoa-story-player`, for images and tables, listen to a `getResourceDataUrl` function property in the context to use in order to fetch correct url

**Comment by mydu** [comment]
fixed in https://github.com/medialab/fonio/commit/0519daa5759ba8b41a2b79a20fa86c2c2753e79e, https://github.com/medialab/fonio/commit/01c2b70bb2cd20a9bb69d6a4e89bd39b58a7d7d6, https://github.com/medialab/fonio/commit/88d629dae50a875d325d21bc44ea8f863114c6f4,
https://github.com/medialab/quinoa-story-player/commit/d413acac938459a910bf24ff21418830499ac7ee,
https://github.com/medialab/quinoa-server/commit/fd38c04d70fc84778f644318d90d4e78569b8f23
