### ISSUE TITLE
Cursor issue when drag-n-dropping inline items

### ISSUE THREAD

**Issue by robindemourat** [medialab/fonio#190]
**Describe the bug**
Cursor does not come back to the right place after having dnd an inline item.

**To Reproduce**
1. Go to the editor
2. Write a begining of sentence
3. Drag a glossary or link at the end of your line

**Observed behavior**
The cursor comes back somewhere very earlier that the point of text which was edited.

**Expected behavior**
It should come back just after the inserted text.

**Screenshots**
![dnd-bug](https://user-images.githubusercontent.com/1876890/44470039-0f939400-a629-11e8-9406-7e08ecbf7b07.gif)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome

**Comment by mydu** [comment]
Investigation: might caused by the incorrect calculation on `endSelection` in scholar-draft

https://github.com/peritext/scholar-draft/blob/0fcc6320cca42231fae65ed2703388fa30bad3ce/src/utils.js#L176
https://github.com/peritext/scholar-draft/blob/0fcc6320cca42231fae65ed2703388fa30bad3ce/src/utils.js#L177

remove `selectedText.length` would fix the issue, need to be verified in detail
